### ISSUE TITLE
Where is it?

### ISSUE THREAD

**Issue by crazy4groovy** [patrickkettner/modernizr-blessed#1]
https://www.youtube.com/watch?v=yUpmf8ZD5UQ

Can't wait man! :wink:

**Comment by paulirish** [comment]
WHAT IS THIS SORCERY!?!?!?

im freaking out man

**Comment by patrickkettner** [comment]
@crazy4groovy - it's here now! Thank you for your patience :]

@paulirish would love to show you it sometime :D

**Comment by paulirish** [comment]
# Hero!
